apiVersion: v1
kind: Service
metadata:
  name: kafka-1-ip-service
spec:
  type: {{.Values.service1.type}}
  selector:
    component: kafka-1
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092



  
