apiVersion: v1
kind: Service
metadata:
  name: kafka-2-ip-service
spec:
  type: {{.Values.service2.type}} 
  selector:
    component: kafka-2
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092



  
