apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ip-service
spec:
  type: {{.Values.service.type}}
  selector:
    app: zookeeper-1
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181


  
